### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by tmos** [xypiie/spread0r#3]
Hi,
Is it possible to override GTK colors with something like a CSS file ? It could be nice, to : 
- remove the white frame
- make a dark color scheme

It is really an awesome tool for reading, but colors are ruinning my eyes _o_

**Comment by xypiie** [comment]
There should be some theme config file for gtk, where you can set the general look&feel.  For Linux it is ~/.gtkrc-2.0 there are even a lot of themes available at http://gnome-look.org/ .  For the label which is showing the flashing text, you could directly change the colors in the perl script.  You'll easily find it in the variable declaration of  "$span_black_open" and "$span_blue_open".

**Comment by tmos** [comment]
Thanks for the script variables.

Actually I know it for GTK, I wanted to change the theme _just_ for this application. I found this, if it interest somebody : http://urukrama.wordpress.com/2008/07/13/setting-a-custom-gtk-theme-for-specific-applications/

By the way; here is a way to include spread0r to the system : http://florian1.tk/blog/?p=215
For non-french speakers : 

In ~/bin, create a bash script : 

```
#!/bin/bash
cd ~/spread0r/install/directory
xclip -o > /tmp/gritz.txt
./gritz.pl -w 400 /tmp/gritz.txt
rm tmp/gritz.txt
```

Then create a keyboard shortcut, and you'll be able to select any text you want and read it with spread0r just with hitting the keyboard shortcut you seted-up.
