### ISSUE TITLE
Usable for PDFs?

### ISSUE THREAD

**Issue by orschiro** [xypiie/spread0r#9]
Hi there, 

I started a discussion on [Reddit](http://www.reddit.com/r/linux/comments/2011nu/is_there_a_spritz_speed_reading_tool_for_pdf/) on spritz implementations for reading PDF files. Yours was suggested as one of the solutions. 

How would you convert PDFs to text in order to read it with spread0r?

Or do you know a native application that can directly speed read PDFs?

Thanks!

**Comment by jinformatique** [comment]
On GNU/Linux there is pdf2txt command included in the package python-pdfminer
Have a look at: http://dev.man-online.org/man1/pdf2txt/

**Comment by orschiro** [comment]
Awesome! Works great.

You might want to add this piece of information to your `README.md`?

Thanks again!

**Comment by orschiro** [comment]
Added the information to the README. 

Thanks again!

https://github.com/xypiie/spread0r/pull/13
